"""
PDF & CSV parser tests — run with:  python tests/test_parser.py
Tests all 6 Saudi bank formats + the real Riyad Bank and ANB PDFs if present.
"""

import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
sys.stdout.reconfigure(encoding='utf-8')

from api.parsers.pdf_parser import parse_pdf
from api.parsers.csv_parser import parse_csv

HERE = os.path.dirname(__file__)

PASS = '\033[92m[PASS]\033[0m'
FAIL = '\033[91m[FAIL]\033[0m'
WARN = '\033[93m[WARN]\033[0m'
SKIP = '\033[90m[SKIP]\033[0m'

passed = failed = skipped = 0


def check(label, path, *, min_txns=1, expect_txns=None, is_csv=False):
    global passed, failed, skipped
    if not os.path.exists(path):
        print(f'{SKIP} {label:35}  (file not found)')
        skipped += 1
        return

    try:
        if is_csv:
            with open(path, 'rb') as f:
                result = parse_csv(f)
        else:
            result = parse_pdf(path)

        n = len(result)
        strategy = result[0].get('_strategy', 'csv') if result else 'none'

        # Basic validations
        assert n >= min_txns, f'expected >={min_txns} txns, got {n}'
        if expect_txns:
            assert n == expect_txns, f'expected {expect_txns} txns, got {n}'

        # Every row must have date, merchant, amount
        for t in result:
            assert t.get('date'),     f'missing date in row: {t}'
            assert t.get('merchant'), f'missing merchant in row: {t}'
            assert isinstance(t.get('amount'), float), f'amount not float: {t}'

        # At least one debit (negative) should exist for any realistic statement
        has_debit = any(t['amount'] < 0 for t in result)
        warn = '' if has_debit else f'  {WARN} no debits found'

        print(f'{PASS} {label:35}  {n:3} txns  [{strategy}]{warn}')
        passed += 1

    except Exception as e:
        print(f'{FAIL} {label:35}  {e}')
        failed += 1


# ── Sample PDFs (generated by create_test_pdfs.py) ─────────────────────────
print('\n── Sample PDFs (synthetic) ────────────────────────────────────────────')
check('Al-Rajhi (sample)',    os.path.join(HERE, 'sample_alrajhi.pdf'), expect_txns=26)
check('Ahli / SNB (sample)',  os.path.join(HERE, 'sample_ahli.pdf'),    expect_txns=26)
check('Inma (sample)',        os.path.join(HERE, 'sample_inma.pdf'),    expect_txns=26)
check('Riyad Bank (sample)',  os.path.join(HERE, 'sample_riyad.pdf'),   expect_txns=26)
check('ANB (sample)',         os.path.join(HERE, 'sample_anb.pdf'),     expect_txns=26)
check('Fransi (sample)',      os.path.join(HERE, 'sample_fransi.pdf'),  expect_txns=26)

# ── Real PDFs (user's actual bank statements in Downloads) ──────────────────
DOWNLOADS = r'C:\Users\mohmmed_ah99\Downloads'
print('\n── Real PDFs (actual bank statements) ─────────────────────────────────')
check('Riyad Bank (real)',
      os.path.join(DOWNLOADS, 'كشف الحساب.pdf'),          min_txns=30)
check('ANB (real)',
      os.path.join(DOWNLOADS, 'كشف الحساب العربي .pdf'),  min_txns=30)
check('SC India / fake (real)',
      os.path.join(DOWNLOADS, 'كشف الحساب وهمي.pdf'),     min_txns=20)

# ── CSV ─────────────────────────────────────────────────────────────────────
print('\n── CSV ─────────────────────────────────────────────────────────────────')
check('Test CSV',
      r'C:\Users\mohmmed_ah99\test_statement.csv',         min_txns=5, is_csv=True)

# ── Summary ─────────────────────────────────────────────────────────────────
total = passed + failed + skipped
print(f'\n{"="*60}')
print(f'Results: {passed} passed  |  {failed} failed  |  {skipped} skipped  '
      f'(total {total})')
if failed:
    print('Some tests FAILED — check output above.')
    sys.exit(1)
else:
    print('All tests passed.')
